// libs/react-components/src/lib/input/input.tsx
import { useEffect, useRef } from "react";
import { format, isValid, parseISO } from "date-fns";
import { GoAAutoCapitalize, GoADate, GoAIconType, GoAInputOnBlurDetail, GoAInputOnChangeDetail, GoAInputOnFocusDetail, GoAInputOnKeyPressDetail, GoAInputType, Margins } from "@abgov/common";

interface WCProps extends Margins {
  ref?: React.MutableRefObject<HTMLInputElement | null>;
  type?: GoAInputType;
  name: string;
  value?: string;
  id?: string;
  autocapitalize?: GoAAutoCapitalize;
  debounce?: number;
  placeholder?: string;
  leadingicon?: string;
  trailingicon?: string;
  variant: string;
  disabled?: boolean;
  error?: boolean;
  readonly?: boolean;
  focused?: boolean;
  handletrailingiconclick: boolean;
  width?: string;
  prefix?: string;
  suffix?: string;
  arialabel?: string;

  // type=number
  min?: string | number;
  max?: string | number;
  step?: number;
  maxlength?: number;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-input": WCProps & React.HTMLAttributes<HTMLInputElement>;
    }
  }
}

interface BaseProps extends Margins {
  // required
  name: string;

  // optional
  id?: string;
  debounce?: number;
  disabled?: boolean;
  autoCapitalize?: GoAAutoCapitalize;
  placeholder?: string;
  leadingIcon?: GoAIconType;
  trailingIcon?: GoAIconType;
  onTrailingIconClick?: () => void;
  variant?: "goa" | "bare";
  focused?: boolean;
  readonly?: boolean;
  error?: boolean;
  width?: string;
  prefix?: string;
  suffix?: string;
  testId?: string;
  ariaLabel?: string;
  leadingContent?: React.ReactNode;
  trailingContent?: React.ReactNode;
  maxLength?: number;
}

type OnChange<T = string> = (detail: GoAInputOnChangeDetail<T>) => void;
type OnFocus<T = string> = (detail: GoAInputOnFocusDetail<T>) => void;
type OnBlur<T = string> = (detail: GoAInputOnBlurDetail<T>) => void;
type OnKeyPress<T = string> = (detail: GoAInputOnKeyPressDetail<T>) => void;

export interface GoAInputProps extends BaseProps {
  onChange: OnChange<string>;
  value?: string;
  min?: number | string;
  max?: number | string;
  step?: number;
  onFocus?: OnFocus<string>;
  onBlur?: OnBlur<string>;
  onKeyPress?: OnKeyPress<string>;
}

interface GoANumberInputProps extends BaseProps {
  onChange: OnChange<number>;
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  onFocus?: OnFocus<number>;
  onBlur?: OnBlur<number>;
  onKeyPress?: OnKeyPress<number>;
}

interface GoADateInputProps extends BaseProps {
  onChange: OnChange<GoADate>;
  value?: GoADate;
  min?: GoADate;
  max?: GoADate;
  step?: number;
  onFocus?: OnFocus<GoADate>;
  onBlur?: OnBlur<GoADate>;
  onKeyPress?: OnKeyPress<GoADate>;
}

export function GoAInput({
  id,
  debounce,
  name,
  type,
  autoCapitalize,
  leadingIcon,
  trailingIcon,
  variant = "goa",
  focused,
  disabled,
  readonly,
  value,
  placeholder,
  error,
  width,
  testId,
  min,
  max,
  step,
  prefix,
  suffix,
  ariaLabel,
  mt,
  mr,
  mb,
  ml,
  leadingContent,
  trailingContent,
  maxLength,
  onTrailingIconClick,
  onChange,
  onFocus,
  onBlur,
  onKeyPress,
}: GoAInputProps & { type?: GoAInputType }): JSX.Element {
  const ref = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;
    const changeListener = (e: Event) => {
      const detail = (e as CustomEvent<GoAInputOnChangeDetail>).detail;
      onChange(detail);
    };
    const clickListener = () => {
      onTrailingIconClick?.();
    };

    const focusListener = (e: Event) => {
      const detail = (e as CustomEvent<GoAInputOnFocusDetail>).detail;
      onFocus?.(detail);
    };

    const blurListener = (e: Event) => {
      const detail = (e as CustomEvent<GoAInputOnBlurDetail>).detail;
      onBlur?.(detail);
    };

    const keypressListener = (e: Event) => {
      const detail = (e as CustomEvent<GoAInputOnKeyPressDetail>).detail;
      onKeyPress?.(detail);
    }

    current.addEventListener("_change", changeListener);
    current.addEventListener("_trailingIconClick", clickListener);
    current.addEventListener("_focus", focusListener);
    current.addEventListener("_blur", blurListener);
    current.addEventListener("_keyPress", keypressListener);

    return () => {
      current.removeEventListener("_change", changeListener);
      current.removeEventListener("_trailingIconClick", clickListener);
      current.removeEventListener("_focus", focusListener);
      current.removeEventListener("_blur", blurListener);
      current.removeEventListener("_keyPress", keypressListener);
    };
  }, [ref, onChange, onTrailingIconClick, onFocus, onBlur, onKeyPress]);

  return (
    <goa-input
      ref={ref}
      debounce={debounce}
      focused={focused}
      type={type}
      name={name}
      autocapitalize={autoCapitalize}
      id={id}
      leadingicon={leadingIcon}
      trailingicon={trailingIcon}
      variant={variant}
      disabled={disabled}
      readonly={readonly}
      placeholder={placeholder}
      error={error}
      data-testid={testId}
      value={value}
      width={width}
      min={min}
      max={max}
      step={step}
      maxlength={maxLength}
      prefix={prefix}
      suffix={suffix}
      arialabel={ariaLabel}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      handletrailingiconclick={!!onTrailingIconClick}
    >
      {leadingContent && <div slot="leadingContent">{leadingContent}</div>}
      {trailingContent && <div slot="trailingContent">{trailingContent}</div>}
    </goa-input>
  );
}

const onDateChangeHandler = (onChange: OnChange<GoADate>) => {
  return ({ name, value }: GoAInputOnChangeDetail<string | Date>) => {
    if (!value) {
      onChange({ name, value: "" });
      return;
    }
    // valid string date
    if (typeof value === "string" && isValid(new Date(value))) {
      onChange({ name, value: parseISO(value) });
      return;
    }
    // valid date
    if (isValid(value)) {
      onChange({ name, value });
      return;
    }
  };
};

const onTimeChangeHandler = (onChange: OnChange) => {
  return ({ name, value }: GoAInputOnChangeDetail) => {
    if (!value) {
      onChange({ name, value: "" });
      return;
    }
    onChange({ name, value });
  };
};

function toString(value: GoADate | null | undefined, tmpl = "yyyy-MM-dd"): string {
  if (!value) {
    return "";
  }
  if (typeof value === "string") {
    return format(parseISO(value), tmpl);
  }
  if (value.toISOString() === new Date(0).toISOString()) {
    return "";
  }
  return format(value, tmpl);
}

export function GoAInputText(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="text" />;
}

export function GoAInputPassword(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="password" />;
}

export function GoAInputDate({
  value,
  min = "",
  max = "",
  ...props
}: GoADateInputProps): JSX.Element {
  return (
    <GoAInput
      {...props}
      type="date"
      onChange={onDateChangeHandler(props.onChange)}
      min={toString(min)}
      max={toString(max)}
      value={toString(value)}
    />
  );
}

export function GoAInputTime({
  value,
  min = "",
  max = "",
  ...props
}: GoAInputProps): JSX.Element {
  return (
    <GoAInput
      {...props}
      onChange={onTimeChangeHandler(props.onChange)}
      value={value}
      type="time"
    />
  );
}

export function GoAInputDateTime({
  value,
  min = "",
  max = "",
  ...props
}: GoADateInputProps): JSX.Element {
  return (
    <GoAInput
      {...props}
      onChange={onDateChangeHandler(props.onChange)}
      value={toString(value, "yyyy-MM-dd'T'HH:mm")}
      type="datetime-local"
    />
  );
}

export function GoAInputEmail(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="email" />;
}

export function GoAInputSearch(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="search" trailingIcon="search" />;
}

export function GoAInputUrl(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="url" />;
}

export function GoAInputTel(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="tel" />;
}

export function GoAInputFile(props: GoAInputProps): JSX.Element {
  return (
    <input
      id={props.id}
      name={props.name}
      type="file"
      onChange={(e) => props.onChange({ name: e.target.name, value: e.target.value })}
      style={{ backgroundColor: "revert" }}
    />
  );
}

export function GoAInputMonth(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="month" />;
}

export function GoAInputNumber({
  min = Number.MIN_VALUE,
  max = Number.MAX_VALUE,
  value,
  ...props
}: GoANumberInputProps): JSX.Element {
  const onNumberChange = ({ name, value }: GoAInputOnChangeDetail) => {
    props.onChange({ name, value: parseFloat(value) });
  };
  const onFocus = ({ name, value }: GoAInputOnFocusDetail) => {
    props.onFocus?.({ name, value: parseFloat(value) });
  };
  const onBlur = ({ name, value }: GoAInputOnBlurDetail) => {
    props.onBlur?.({ name, value: parseFloat(value) });
  };
  const onKeyPress = ({ name, value, key }: GoAInputOnKeyPressDetail) => {
    props.onKeyPress?.({ name, value: parseFloat(value), key: parseInt(key) });
  };
  return (
    <GoAInput
      {...props}
      onChange={onNumberChange}
      min={min?.toString()}
      max={max?.toString()}
      value={value?.toString()}
      onFocus={onFocus}
      onBlur={onBlur}
      type="number"
      onKeyPress={onKeyPress}
    />
  );
}

export function GoAInputRange(props: GoAInputProps): JSX.Element {
  return <GoAInput {...props} type="range" />;
}

export default GoAInput;

// libs/angular-components/src/lib/components/input/input.ts
import { GoAIconType, GoAInputOnBlurDetail, GoAInputOnChangeDetail, GoAInputOnFocusDetail, GoAInputOnKeyPressDetail, GoAInputType, Spacing } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-input",
  template: `
    <goa-input
      [type]="type"
      [name]="name"
      [value]="value"
      [autocapitalize]="autoCapitalize"
      [placeholder]="placeholder"
      [leadingicon]="leadingIcon"
      [trailingicon]="trailingIcon"
      [variant]="variant"
      [disabled]="disabled"
      [focused]="focused"
      [readonly]="readonly"
      [error]="error"
      [testId]="testId"
      [width]="width"
      [arialabel]="ariaLabel"
      [arialabelledby]="ariaLabelledBy"
      [min]="min"
      [max]="max"
      [step]="step"
      [prefix]="prefix"
      [suffix]="suffix"
      [debounce]="debounce"
      [maxlength]="maxLength"
      [id]="id"
      [mt]="mt"
      [mr]="mr"
      [mb]="mb"
      [ml]="ml"  
      (ontrailingiconclick)="_onTrailingIconClick($event)"
      (onchange)="_onChange($event)"
      (onfocus)="_onFocus($event)"
      (onblur)="_onBlur($event)"
      (onkeypress)="_onKeyPress($event)"
    >
    </goa-input>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAInput {
  @Input() type?: GoAInputType = "text";
  @Input() name?: string;
  @Input() value?: string = "";
  @Input() autoCapitalize?: boolean;
  @Input() placeholder?: string;
  @Input() leadingIcon?: GoAIconType;
  @Input() trailingIcon?: GoAIconType;
  @Input() variant?: string;
  @Input() disabled?: boolean;
  @Input() focused?: boolean;
  @Input() readonly?: boolean;
  @Input() error?: boolean;
  @Input() testId?: string;
  @Input() width?: string;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledBy?: string;
  @Input() min?: number;
  @Input() max?: number;
  @Input() step?: number;
  @Input() prefix?: string;
  @Input() suffix?: string;
  @Input() debounce?: boolean;
  @Input() maxLength?: number;
  @Input() id?: string;
  @Input() mt?: Spacing;
  @Input() mr?: Spacing;
  @Input() mb?: Spacing;
  @Input() ml?: Spacing;

  @Output() onTrailingIconClick = new EventEmitter();
  @Output() onFocus = new EventEmitter<GoAInputOnFocusDetail>();
  @Output() onBlur = new EventEmitter<GoAInputOnBlurDetail>();
  @Output() onKeyPress = new EventEmitter<GoAInputOnKeyPressDetail>();
  @Output() onChange = new EventEmitter<GoAInputOnChangeDetail>();

  _onTrailingIconClick(_: Event) {
    this.onTrailingIconClick.emit();
  }

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoAInputOnChangeDetail>).detail;
    this.onChange.emit(detail);
  }

  _onKeyPress(e: Event) {
    const detail = (e as CustomEvent<GoAInputOnKeyPressDetail>).detail
    this.onKeyPress.emit(detail);
  }

  _onFocus(e: Event) {
    const detail = (e as CustomEvent<GoAInputOnFocusDetail>).detail
    this.onFocus.emit(detail);
  }

  _onBlur(e: Event) {
    const detail = (e as CustomEvent<GoAInputOnBlurDetail>).detail
    this.onBlur.emit(detail);
  }
}
