// libs/angular-components/src/lib/components/form-item/form-item.ts
import { GoAFormItemLabelSize, GoAFormItemRequirement, Spacing } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-form-item",
  template: `
    <goa-form-item
      [label]="label"
      [labelsize]="labelSize"
      [helptext]="helpText"
      [error]="error"
      [requirement]="requirement"
      [id]="id"
      [mt]="mt"
      [mb]="mb"
      [mr]="mr"
      [ml]="ml"
    >
      <ng-content />
    </goa-form-item>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAFormItem {
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() mr?: Spacing;
  @Input() ml?: Spacing;
  @Input() label?: string;
  @Input() labelSize?: GoAFormItemLabelSize;
  @Input() helpText?: string;
  @Input() error?: string;
  @Input() requirement?: GoAFormItemRequirement;
  @Input() id?: string;
}

// libs/react-components/src/lib/form-item/form-item.tsx
import { GoAFormItemLabelSize, GoAFormItemRequirement, Margins } from "@abgov/common";

interface WCProps extends Margins {
  label?: string;
  labelsize?: GoAFormItemLabelSize;
  requirement?: GoAFormItemRequirement;
  error?: string;
  helptext?: string;
  id?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-form-item": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAFormItemProps extends Margins {
  label?: string;
  labelSize?: GoAFormItemLabelSize;
  requirement?: GoAFormItemRequirement;
  error?: string;
  helpText?: string;
  children?: React.ReactNode;
  testId?: string;
  id?: string;
}

export function GoAFormItem({
  children,
  helpText,
  error,
  requirement,
  label,
  labelSize,
  mt,
  mr,
  mb,
  ml,
  testId,
  id,
}: GoAFormItemProps): JSX.Element {
  return (
    <goa-form-item
      label={label}
      labelsize={labelSize}
      error={error}
      requirement={requirement}
      helptext={helpText}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      data-testid={testId}
      id={id}
    >
      {children}
    </goa-form-item>
  );
}

export default GoAFormItem;
