// libs/react-components/src/lib/button/button.tsx
import { ReactNode, useEffect, useRef } from "react";
import { GoAButtonSize, GoAButtonType, GoAButtonVariant, GoAIconType, Margins } from "@abgov/common";

interface WCProps extends Margins {
  type?: GoAButtonType;
  size?: GoAButtonSize;
  variant?: GoAButtonVariant;
  disabled?: boolean;
  leadingicon?: string;
  trailingicon?: string;
  ref: React.RefObject<HTMLElement>;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-button": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAButtonProps extends Margins {
  type?: GoAButtonType;
  size?: GoAButtonSize;
  variant?: GoAButtonVariant;
  disabled?: boolean;
  leadingIcon?: GoAIconType;
  trailingIcon?: GoAIconType;
  onClick?: () => void;
  testId?: string;
  children?: ReactNode;
}

export function GoAButton({
  disabled = false,
  type = "primary",
  size,
  variant,
  leadingIcon,
  trailingIcon,
  testId,
  children,
  onClick,
  mt,
  mr,
  mb,
  ml,
}: GoAButtonProps): JSX.Element {
  const el = useRef<HTMLElement>(null);
  useEffect(() => {
    if (!el.current) {
      return;
    }
    if (!onClick) {
      return;
    }
    const current = el.current;
    const listener = () => {
      onClick();
    };

    current.addEventListener("_click", listener);
    return () => {
      current.removeEventListener("_click", listener);
    };
  }, [el, onClick]);

  return (
    <goa-button
      ref={el}
      type={type}
      size={size}
      variant={variant}
      disabled={disabled}
      leadingicon={leadingIcon}
      trailingicon={trailingIcon}
      data-testid={testId}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    >
      {children}
    </goa-button>
  );
}

export default GoAButton;

// libs/angular-components/src/lib/components/button/button.ts
import { GoAButtonSize, GoAButtonType, GoAButtonVariant, GoAIconType } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-button",
  template: `
    <goa-button 
      [type]="type"
      [size]="size"
      [variant]="variant"
      [disabled]="disabled"
      [leadingicon]="leadingIcon"
      [trailingicon]="trailingIcon"
      [testid]="testId"
      [mt]="mt"
      [mb]="mb"
      [ml]="ml"
      [mr]="mr"
      (_click)="_onClick($event)"
    >
      <ng-content />
    </goa-button>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAButton {
  @Input() type?: GoAButtonType;
  @Input() size?: GoAButtonSize;
  @Input() variant?: GoAButtonVariant;
  @Input() disabled?: boolean;
  @Input() leadingIcon?: GoAIconType;
  @Input() trailingIcon?: GoAIconType;
  @Input() testId?: string;
  @Input() mt?: string;
  @Input() mb?: string;
  @Input() ml?: string;
  @Input() mr?: string;

  @Output() onClick = new EventEmitter();

  _onClick(_: any) {
    this.onClick.emit();
  }
}
