// libs/angular-components/src/lib/components/textarea/textarea.ts
import { GoATextAreaCountBy } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

export type GoATextAreaOnChangeDetail = {
  name: string;
  value: string;
}

export type GoATextAreaOnKeyPressDetail = {
  name: string;
  value: string;
  key: string;
}

@Component({
  standalone: true,
  selector: "goax-textarea",
  template: `
    <goa-textarea
      [name]="name"
      [value]="value"
      [id]="id"
      [placeholder]="placeholder"
      [rows]="rows"
      [error]="error"
      [disabled]="disabled"
      [width]="width"
      [testid]="testId"
      [arialabel]="ariaLabel"
      [countby]="countBy"
      [maxcount]="maxCount"
      (_change)="_onChange($event)"
      (_keypress)="_onKeyPress($event)"
    >
    </goa-textarea>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoATextArea {
  @Input({ required: true }) name!: string;
  @Input() value?: string = "";
  @Input() id?: string;
  @Input() placeholder?: string;
  @Input() rows?: number;
  @Input() error?: boolean;
  @Input() disabled?: boolean;
  @Input() width?: string;
  @Input() testId?: string;
  @Input() ariaLabel?: string;
  @Input() countBy?: GoATextAreaCountBy;
  @Input() maxCount?: number;

  @Output() onChange = new EventEmitter<GoATextAreaOnChangeDetail>();
  @Output() onKeyPress = new EventEmitter<GoATextAreaOnKeyPressDetail>();

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoATextAreaOnChangeDetail>).detail;
    this.onChange.emit(detail)
  }

  _onKeyPress(e: any) {
    const detail = (e as CustomEvent<GoATextAreaOnKeyPressDetail>).detail;
    this.onKeyPress.emit(detail)
  }
}

// libs/react-components/src/lib/textarea/textarea.tsx
import { GoATextAreaCountBy, Margins } from "@abgov/common";
import { useEffect, useRef } from "react";

interface WCProps extends Margins {
  ref: React.Ref<HTMLTextAreaElement>;
  name: string;
  value?: string;
  placeholder?: string;
  rows?: number;
  error?: boolean;
  disabled?: boolean;
  width?: string;
  arialabel?: string;
  countby?: GoATextAreaCountBy;
  maxcount?: number;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-textarea": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoATextAreaProps extends Margins {
  name: string;
  value?: string;
  id?: string;
  placeholder?: string;
  rows?: number;
  error?: boolean;
  disabled?: boolean;
  width?: string;
  testId?: string;
  ariaLabel?: string;
  countBy?: GoATextAreaCountBy;
  maxCount?: number;

  onChange: (name: string, value: string) => void;
  onKeyPress?: (name: string, value: string, key: string) => void;
}

export function GoATextarea({
  name,
  value,
  placeholder,
  rows,
  disabled,
  countBy,
  maxCount,
  width,
  testId,
  error,
  ariaLabel,
  mt,
  mr,
  mb,
  ml,
  onChange,
  onKeyPress,
}: GoATextAreaProps): JSX.Element {
  const el = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!el.current) {
      return;
    }
    const current = el.current;
    const listener: EventListener = (e: unknown) => {
      const { name, value } = (e as CustomEvent).detail;
      onChange(name, value);
    };

    current.addEventListener("_change", listener);
    return () => {
      current.removeEventListener("_change", listener);
    };
  }, [el, onChange]);


  useEffect(() => {
    if (!el.current) {
      return;
    }
    const current = el.current;
    const keypressListener = (e: unknown) => {
      const { name, value, key } = (e as CustomEvent).detail;
      onKeyPress?.(name, value, key);
    }

    current.addEventListener("_keyPress", keypressListener);
    return () => {
      current.removeEventListener("_keyPress", keypressListener);
    };
  }, [el, onKeyPress]);

  return (
    <goa-textarea
      ref={el}
      name={name}
      placeholder={placeholder}
      value={value}
      rows={rows}
      disabled={disabled}
      countby={countBy}
      maxcount={maxCount}
      width={width}
      error={error}
      data-testid={testId}
      arialabel={ariaLabel}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    ></goa-textarea>
  );
}

export {GoATextarea as GoATextArea}
export default GoATextarea;
