// libs/react-components/src/lib/button-group/button-group.tsx
import { GoAButtonGroupAlignment, GoAButtonGroupGap, Margins } from "@abgov/common";

interface WCProps extends Margins {
  alignment: GoAButtonGroupAlignment;
  gap?: GoAButtonGroupGap;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-button-group": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAButtonGroupProps extends Margins {
  alignment: GoAButtonGroupAlignment;
  gap?: GoAButtonGroupGap;
  testId?: string;
  children?: React.ReactNode;
}

export function GoAButtonGroup({
  alignment,
  gap,
  testId,
  children,
  mt,
  mr,
  mb,
  ml,
}: GoAButtonGroupProps): JSX.Element {
  return (
    <goa-button-group
      alignment={alignment}
      gap={gap}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      data-testid={testId}
    >
      {children}
    </goa-button-group>
  );
}

export default GoAButtonGroup;

// libs/angular-components/src/lib/components/button-group/button-group.ts
import { GoAButtonGroupAlignment, GoAButtonGroupGap, Spacing } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-button-group",
  template: `
    <goa-button-group
      [alignment]="alignment"
      [gap]="gap"
      [testid]="testId"
      [mt]="mt"
      [mb]="mb"
      [ml]="ml"
      [mr]="mr"
    >
      <ng-content />
    </goa-button-group>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAButtonGroup {
  @Input() alignment?: GoAButtonGroupAlignment;
  @Input() gap?: GoAButtonGroupGap;
  @Input() testId?: string;
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() ml?: Spacing;
  @Input() mr?: Spacing;
}
