// libs/angular-components/src/lib/components/checkbox/checkbox.ts
import { GoACheckboxOnChangeDetail } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-checkbox",
  template: `<goa-checkbox
    [name]="name"
    [checked]="checked"
    [disabled]="disabled"
    [error]="error"
    [text]="text"
    [value]="value"
    [testid]="testId"
    [arialabel]="ariaLabel"
    [description]="description"
    (_change)="_onChange($event)"
  >
    <ng-content />
  </goa-checkbox>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoACheckbox {
  @Input() name?: string;
  @Input() checked?: boolean;
  @Input() disabled?: boolean;
  @Input() error?: boolean;
  @Input() text?: string;
  @Input() value?: string | number | boolean;
  @Input() testId?: string;
  @Input() ariaLabel?: string;
  @Input() description?: string;

  @Output() onChange = new EventEmitter<GoACheckboxOnChangeDetail>();

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoACheckboxOnChangeDetail>).detail;
    this.onChange.emit(detail)
  }
}

// libs/react-components/src/lib/checkbox/checkbox.tsx
import { GoACheckboxOnChangeDetail, Margins } from "@abgov/common";
import { useEffect, useRef } from "react";

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-checkbox": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface WCProps extends Margins {
  ref: React.RefObject<HTMLElement>;
  id?: string;
  name: string;
  checked: boolean;
  disabled?: boolean;
  error?: boolean;
  text?: string;
  value?: string | number | boolean;
  arialabel?: string;
  description?: string | React.ReactNode;
}

/* eslint-disable-next-line */
export interface GoACheckboxProps extends Margins {
  id?: string;
  name: string;
  checked: boolean;
  disabled?: boolean;
  error?: boolean;
  text?: string;
  value?: string | number | boolean;
  children?: React.ReactNode;
  testId?: string;
  ariaLabel?: string;
  description?: string | React.ReactNode;
  onChange?: (detail: GoACheckboxOnChangeDetail) => void;
}

// legacy
export type Props = GoACheckboxProps;

export function GoACheckbox({
  id,
  name,
  testId,
  error,
  disabled,
  checked,
  value,
  text,
  description,
  children,
  onChange,
  ariaLabel,
  mt,
  mr,
  mb,
  ml,
}: GoACheckboxProps): JSX.Element {
  const el = useRef<HTMLElement>(null);
  useEffect(() => {
    if (!el.current) {
      return;
    }
    const current = el.current;
    const listener = (e: Event) => {
      const detail = (e as CustomEvent<GoACheckboxOnChangeDetail>).detail;
      onChange?.(detail);
    };

    current.addEventListener("_change", listener);

    return () => {
      current.removeEventListener("_change", listener);
    };
  }, [name, onChange]);

  return (
    <goa-checkbox
      data-testid={testId}
      ref={el}
      id={id}
      name={name}
      error={error}
      checked={checked}
      disabled={disabled}
      text={text}
      value={value}
      arialabel={ariaLabel}
      description={typeof description === "string" ? description : undefined}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    >
      {description && typeof description !== "string" && <div slot="description">{description}</div>}
      {children}
    </goa-checkbox>
  );
}

export default GoACheckbox;
