// libs/angular-components/src/lib/components/calendar/calendar.ts
import { GoACalendarOnChangeDetail } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-calendar",
  template: `
    <goa-calendar
      [name]="name"
      [value]="value"
      [min]="min"
      [max]="max"
      (_change)="_onChange($event)"
    >
      <ng-content />
    </goa-calendar>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoACalendar {
  name?: string;
  value?: Date;
  min?: Date;
  max?: Date;

  @Output() onChange = new EventEmitter<GoACalendarOnChangeDetail>();

  _onChange(e: Event) {
    const details = (e as CustomEvent<GoACalendarOnChangeDetail>).detail;
    this.onChange.emit(details)
  }
}

// libs/react-components/src/lib/calendar/calendar.tsx
import { useEffect, useRef } from "react";
import { GoACalendarOnChangeDetail, Margins } from "@abgov/common";

interface WCProps extends Margins {
  ref: React.RefObject<HTMLElement>;
  name?: string;
  value?: string;
  min?: string;
  max?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-calendar": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoACalendarProps extends Margins {
  name?: string;
  value?: Date;
  min?: Date;
  max?: Date;
  onChange: (details: GoACalendarOnChangeDetail) => void;
}

export function GoACalendar({
  name,
  value,
  min,
  max,
  mt,
  mr,
  mb,
  ml,
  onChange,
}: GoACalendarProps): JSX.Element {
  const ref = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;
    current.addEventListener("_change", (e: Event) => {
      onChange({ 
        name: name || "", 
        value: (e as CustomEvent).detail.value,
      });
    });
  });

  return (
    <goa-calendar
      ref={ref}
      name={name}
      value={value?.toISOString()}
      min={min?.toISOString()}
      max={max?.toISOString()}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    />
  );
}

export default GoACalendar;
