// libs/react-components/src/lib/circular-progress/circular-progress.tsx
import { GoACircularProgressSize, GoACircularProgressVariant } from "@abgov/common";

interface WCProps {
  variant?: GoACircularProgressVariant;
  size?: GoACircularProgressSize;
  message?: string;
  visible?: string;
  progress?: number;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-circular-progress": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoACircularProgressProps {
  variant?: GoACircularProgressVariant;
  size?: GoACircularProgressSize;
  message?: string;
  visible?: boolean;
  progress?: number;
  testId?: string;
}

export const GoACircularProgress = ({
  visible,
  message,
  progress,
  variant,
  size,
  testId,
}: GoACircularProgressProps) => {
  return (
    <goa-circular-progress
      visible={visible ? "true" : "false"}
      message={message}
      progress={progress}
      variant={variant}
      size={size}
      data-testid={testId}
    />
  );
}

export default GoACircularProgress;

// libs/angular-components/src/lib/components/circular-progress/circular-progress.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

import { GoACircularProgressSize, GoACircularProgressVariant } from "@abgov/common"

@Component({
  standalone: true,
  selector: "goax-circular-progress",
  template: `<goa-circular-progress
    [variant]="variant"
    [size]="size"
    [message]="message"
    [visible]="visible"
    [progress]="progress"
    [testid]="testId"
  >
    <ng-content />
  </goa-circular-progress>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoACircularProgress {
  @Input() variant?: GoACircularProgressVariant;
  @Input() size?: GoACircularProgressSize;
  @Input() message?: string;
  @Input() visible?: boolean;
  @Input() progress?: number;
  @Input() testId?: string;
}
