// libs/angular-components/src/lib/components/file-upload-input/file-upload-input.ts
import { GoAFileUploadInputOnSelectFileDetail, GoAFileUploadInputVariant, Spacing } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-file-upload-input",
  template: `<goa-file-upload-input
    [variant]="variant"
    [maxfilesize]="maxFileSize"
    [id]="id"
    [mt]="mt"
    [mb]="mb"
    [mr]="mr"
    [ml]="ml"
    (_selectfile)="_onSelectFile($event)"
  >
  </goa-file-upload-input>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAFileUploadInput {
  @Input() id?: string = "";
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() mr?: Spacing;
  @Input() ml?: Spacing;
  @Input() variant?: GoAFileUploadInputVariant;
  @Input() maxFileSize?: string;

  @Output() onSelectFile = new EventEmitter<GoAFileUploadInputOnSelectFileDetail>();

  _onSelectFile(e: Event) {
    const detail = (e as CustomEvent<GoAFileUploadInputOnSelectFileDetail>).detail;
    this.onSelectFile.emit(detail);
  }
}

// libs/react-components/src/lib/file-upload-input/file-upload-input.tsx
import { GoAFileUploadInputOnSelectFileDetail, GoAFileUploadInputVariant } from "@abgov/common";
import { useEffect, useRef } from "react";

interface WCProps {
  ref: React.MutableRefObject<HTMLElement | null>;
  variant?: GoAFileUploadInputVariant;
  accept?: string;
  maxfilesize?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-file-upload-input": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoAFileUploadInputProps {
  variant?: GoAFileUploadInputVariant;
  accept?: string;
  maxFileSize?: string;
  onSelectFile: (detail: GoAFileUploadInputOnSelectFileDetail) => void;
}

export function GoAFileUploadInput({
  variant,
  accept,
  maxFileSize,
  onSelectFile,
}: GoAFileUploadInputProps) {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) return;

    const current = el.current;
    const handler = (e: Event) => {
      const detail = (e as CustomEvent<GoAFileUploadInputOnSelectFileDetail>).detail;
      onSelectFile(detail);
    };
    current.addEventListener("_selectFile", handler);
    return () => {
      current.removeEventListener("_selectFile", handler);
    };
  }, [el, onSelectFile]);

  return (
    <goa-file-upload-input
      ref={el}
      variant={variant}
      accept={accept}
      maxfilesize={maxFileSize}
    />
  );
}

export default GoAFileUploadInput;
