// libs/angular-components/src/lib/components/radio-group/radio-group.ts
import { GoARadioGroupOnChangeDetail, GoARadioGroupOrientation } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-radio-group",
  template: `
    <goa-radio-group
      [name]="name"
      [value]="value"
      [disabled]="disabled"
      [orientation]="orientation"
      [testid]="testId"
      [error]="error"
      [arialabel]="ariaLabel"
      (_change)="_onChange($event)"
    >
      <ng-content />
    </goa-radio-group>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoARadioGroup {
  @Input({ required: true }) name!: string;
  @Input() value?: string;
  @Input() disabled?: boolean;
  @Input() orientation?: GoARadioGroupOrientation;
  @Input() testId?: string;
  @Input() error?: boolean;
  @Input() ariaLabel?: string;

  @Output() onChange = new EventEmitter<GoARadioGroupOnChangeDetail>();

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoARadioGroupOnChangeDetail>).detail;
    this.onChange.emit(detail);
  }
}

// libs/react-components/src/lib/radio-group/radio-group.tsx
import { useEffect, useRef } from "react";
import { GoARadioGroupOnChangeDetail, GoARadioGroupOrientation, Margins } from "@abgov/common";

export * from "./radio";


interface WCProps extends Margins {
  ref: React.RefObject<HTMLElement>;
  name: string;
  value?: string;
  orientation?: GoARadioGroupOrientation;
  disabled?: boolean;
  error?: boolean;
  arialabel?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-radio-group": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoARadioGroupProps extends Margins {
  name: string;
  value?: string;
  disabled?: boolean;
  orientation?: GoARadioGroupOrientation;
  testId?: string;
  error?: boolean;
  ariaLabel?: string;
  children?: React.ReactNode;
  onChange: (detail: GoARadioGroupOnChangeDetail) => void;
}

export function GoARadioGroup({
  name,
  value,
  children,
  orientation,
  disabled = false,
  error = false,
  testId,
  ariaLabel,
  mt,
  mr,
  mb,
  ml,
  onChange,
}: GoARadioGroupProps): JSX.Element {

  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) return

    const listener = (e: Event) => {
      if (!onChange) {
        console.warn("Missing onChange function");
        return;
      }
      const detail = (e as CustomEvent<GoARadioGroupOnChangeDetail>).detail;
      onChange(detail);
    };

    const currentEl = el.current;
    currentEl.addEventListener("_change", listener);

    return () => {
      currentEl.removeEventListener("_change", listener);
    };
  }, [name, onChange]);

  return (
    <goa-radio-group
      data-testid={testId}
      ref={el}
      name={name}
      value={value}
      orientation={orientation}
      disabled={disabled}
      error={error}
      arialabel={ariaLabel}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    >
      {children}
    </goa-radio-group>
  );
}

export default GoARadioGroup;
