// libs/react-components/src/lib/side-menu-heading/side-menu-heading.tsx
import { GoAIconType } from "@abgov/common";
import { ReactNode } from "react";

interface WCProps {
  icon?: GoAIconType;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-side-menu-heading": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoASideMenuHeadingProps {
  meta?: ReactNode;
  icon?: GoAIconType
  children?: ReactNode;
}

export function GoASideMenuHeading(props: GoASideMenuHeadingProps) {
  return (
    <goa-side-menu-heading icon={props.icon}>
      {props.children}
      {props.meta && <span slot="meta">{props.meta}</span>}
    </goa-side-menu-heading>
  );
}

export default GoASideMenuHeading;

// libs/angular-components/src/lib/components/side-menu-heading/side-menu-heading.ts
import { GoAIconType } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-side-menu-heading",
  template: `
    <goa-side-menu-heading
      [icon]="icon"
      [meta]="meta"
    >
      <ng-content />
    </goa-side-menu-heading>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoASideMenuHeading {
  @Input() icon!: GoAIconType;
  @Input() meta!: string;
}
