// libs/angular-components/src/lib/components/file-upload-card/file-upload-card.ts
import { GoAFileUploadOnCancelDetail, GoAFileUploadOnDeleteDetail, Spacing } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-file-upload-card",
  template: `<goa-file-upload-card
    [filename]="filename"
    [size]="size"
    [type]="type"
    [progress]="progress"
    [error]="error"
    [mt]="mt"
    [mb]="mb"
    [mr]="mr"
    [ml]="ml"
    (_cancel)="_onCancel()"
    (_delete)="_onDelete()"
  >
  </goa-file-upload-card>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAFileUploadCard {
  @Input({ required: true }) filename!: string;
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() mr?: Spacing;
  @Input() ml?: Spacing;
  @Input() size?: number;
  @Input() type?: string;
  @Input() progress?: number;
  @Input() error?: string;

  @Output() onCancel = new EventEmitter<GoAFileUploadOnCancelDetail>();
  @Output() onDelete = new EventEmitter<GoAFileUploadOnDeleteDetail>();

  _onCancel() {
    this.onCancel.emit({ filename: this.filename })
  }

  _onDelete() {
    this.onDelete.emit({ filename: this.filename })
  }
}

// libs/react-components/src/lib/file-upload-card/file-upload-card.tsx
import { GoAFileUploadOnCancelDetail, GoAFileUploadOnDeleteDetail } from "@abgov/common";
import { useEffect, useRef } from "react";

interface WCProps {
  ref: React.MutableRefObject<HTMLElement | null>;
  filename: string;
  size: number;
  type?: string;
  progress?: number;
  error?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-file-upload-card": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoAFileUploadCardProps {
  filename: string;
  size: number;
  type?: string;
  progress?: number;
  error?: string;
  onDelete?: (detail: GoAFileUploadOnDeleteDetail) => void;
  onCancel?: (detail: GoAFileUploadOnCancelDetail) => void;
}

export function GoAFileUploadCard({
  filename,
  size,
  type,
  progress,
  error,
  onDelete,
  onCancel,
}: GoAFileUploadCardProps) {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) return;

    const current = el.current;
    const deleteHandler = () => onDelete?.({ filename });
    const cancelHandler = () => onCancel?.({ filename });
    current.addEventListener("_delete", deleteHandler);
    current.addEventListener("_cancel", cancelHandler);
    return () => {
      current.removeEventListener("_delete", deleteHandler);
      current.removeEventListener("_cancel", cancelHandler);
    };
  }, [el, onDelete, onCancel]);

  return (
    <goa-file-upload-card
      ref={el}
      filename={filename}
      size={size}
      type={type}
      progress={progress}
      error={error}
    />
  );
}

export default GoAFileUploadCard;
