// libs/react-components/src/lib/form-step/form-step.tsx
import { GoAFormStepStatus } from "@abgov/common";

interface WCProps {
  text: string;
  status?: GoAFormStepStatus;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-form-step": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAFormStepProps {
  text: string;
  status?: GoAFormStepStatus;
}

export function GoAFormStep(props: GoAFormStepProps) {
  return <goa-form-step text={props.text} status={props.status} />;
}

export default GoAFormStep;

// libs/angular-components/src/lib/components/form-step/form-step.ts
import { GoAFormStepStatus } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-form-step",
  template: `
    <goa-form-step
      [text]="text"
      [status]="status"
      [arialabel]="arialabel"
      [childindex]="childindex"
      [enabled]="enabled"
    >
      <ng-content />
    </goa-form-step>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAFormStep {
  @Input() text?: string;
  @Input() status?: GoAFormStepStatus;
  @Input() arialabel?: string;
  @Input() childindex?: string;
  @Input() enabled?: boolean;
}
