// libs/react-components/src/lib/microsite-header/microsite-header.tsx
import { GoALinkTarget, GoAServiceLevel } from "@abgov/common";

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-microsite-header": WCProps &
      React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface WCProps {
  type: GoAServiceLevel;
  version?: string;
  feedbackurl?: string;
  maxcontentwidth?: string;
  feedbackurltarget?: GoALinkTarget
  headerurltarget?: GoALinkTarget;
}

export interface GoAHeaderProps {
  type: GoAServiceLevel;
  version?: string;
  feedbackUrl?: string;
  testId?: string;
  maxContentWidth?: string;
  feedbackUrlTarget?: GoALinkTarget;
  headerUrlTarget?: GoALinkTarget;
}

export function GoAMicrositeHeader({
  type,
  version,
  feedbackUrl,
  maxContentWidth,
  feedbackUrlTarget,
  headerUrlTarget,
  testId,
}: GoAHeaderProps): JSX.Element {
  return (
    <goa-microsite-header
      type={type}
      version={version}
      feedbackurl={feedbackUrl}
      data-testid={testId}
      maxcontentwidth={maxContentWidth}
      feedbackurltarget={feedbackUrlTarget}
      headerurltarget={headerUrlTarget}
    />
  );
}

export default GoAMicrositeHeader;

// libs/angular-components/src/lib/components/microsite-header/microsite-header.ts
import { GoALinkTarget, GoAServiceLevel } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-microsite-header",
  template: `
    <goa-microsite-header
      [type]="type"
      [version]="version"
      [feedbackurl]="feedbackUrl"
      [maxcontentwidth]="maxContentWidth"
      [feedbackurltarget]="feedbackUrlTarget"
      [headerurltarget]="headerUrlTarget"
    >
    </goa-microsite-header>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAMicrositeHeader {
  @Input() type?: GoAServiceLevel;
  @Input() version?: string;
  @Input() feedbackUrl?: string;
  @Input() maxContentWidth?: string;
  @Input() feedbackUrlTarget?: GoALinkTarget;
  @Input() headerUrlTarget?: GoALinkTarget;
}
