// libs/angular-components/src/lib/components/date-picker/date-picker.ts
import { GoADatePickerOnChangeDetail } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-datepicker",
  template: `
    <goa-date-picker 
      [name]="name" 
      [value]="value" 
      [min]="min" 
      [max]="max" 
      (_change)="_onChange($event)"
    >
    </goa-date-picker>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoADatePicker {
  @Input() name?: string;
  @Input() value?: Date | string;
  @Input() min?: Date | string;
  @Input() max?: Date | string;
  @Output() onChange = new EventEmitter<GoADatePickerOnChangeDetail>();

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoADatePickerOnChangeDetail>).detail;
    this.onChange.emit(detail)
  }
}

// libs/react-components/src/lib/date-picker/date-picker.tsx
import { useEffect, useRef } from "react";
import { GoADatePickerOnChangeDetail, Margins } from "@abgov/common";

interface WCProps extends Margins {
  ref: React.RefObject<HTMLElement>;
  name?: string;
  value?: string;
  min?: string;
  max?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-date-picker": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoADatePickerProps extends Margins {
  name?: string;
  value?: Date;
  min?: Date;
  max?: Date;
  onChange: (detail: GoADatePickerOnChangeDetail) => void;
}

export function GoADatePicker({
  name,
  value,
  min,
  max,
  mt,
  mr,
  mb,
  ml,
  onChange,
}: GoADatePickerProps): JSX.Element {
  const ref = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;
    current.addEventListener("_change", (e: Event) => {
      const detail = (e as CustomEvent<GoADatePickerOnChangeDetail>).detail;
      onChange(detail);
    });
  });

  return (
    <goa-date-picker
      ref={ref}
      name={name}
      value={value?.toISOString()}
      min={min?.toISOString()}
      max={max?.toISOString()}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    />
  );
}

export default GoADatePicker;
