// libs/angular-components/src/lib/components/modal/modal.ts
import { GoAModalCalloutVariant, GoAModalTransition } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-modal",
  template: `
    <goa-modal
      [calloutvariant]="calloutVariant"
      [open]="open"
      [maxwidth]="maxWidth"
      [closable]="closable"
      [transition]="transition"
      (_close)="_onClose()"
    >
      <ng-content select="[slot=heading]" />
      <ng-content select="[slot=actions]" />
    </goa-modal>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAModal {
  @Input() calloutVariant?: GoAModalCalloutVariant;
  @Input() open?: boolean;
  @Input() maxWidth?: string;
  @Input() closable: boolean = false;
  @Input() transition?: GoAModalTransition

  @Output() onClose = new EventEmitter();

  _onClose() {
    this.onClose.emit();
  }
}

// libs/react-components/src/lib/modal/modal.tsx
import { GoAModalCalloutVariant, GoAModalTransition } from "@abgov/common";
import { ReactElement, ReactNode, RefObject, useEffect, useRef } from "react";

interface WCProps {
  ref: RefObject<HTMLElement>;
  heading?: ReactNode;
  open?: boolean;
  maxwidth?: string;
  closable?: boolean;
  transition?: GoAModalTransition;
  calloutvariant?: GoAModalCalloutVariant;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-modal": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAModalProps {
  heading?: ReactNode;
  maxWidth?: string;
  actions?: ReactElement;
  onClose?: () => void;
  transition?: GoAModalTransition;
  children?: ReactNode;
  open?: boolean;
  calloutVariant?: GoAModalCalloutVariant;
  testId?: string;
}

export function GoAModal({
  heading,
  children,
  maxWidth,
  open,
  actions,
  transition,
  calloutVariant,
  onClose,
  testId,
}: GoAModalProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) {
      return;
    }
    const current = el.current;
    const listener = () => {
      onClose?.();
    };

    current.addEventListener("_close", listener);
    return () => {
      current.removeEventListener("_close", listener);
    };
  }, [el, onClose]);

  return (
    <goa-modal
      ref={el}
      open={open}
      closable={!!onClose}
      maxwidth={maxWidth}
      transition={transition}
      calloutvariant={calloutVariant}
      data-testid={testId}
    >
      {heading && <div slot="heading">{heading}</div>}
      {actions && <div slot="actions">{actions}</div>}
      {children}
    </goa-modal>
  );
}

export default GoAModal;
