// libs/angular-components/src/lib/components/accordion/accordion.ts
import { GoAAccordionHeadingSize } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-accordion",
  template: `
    <goa-accordion
      [heading]="heading"
      [secondarytext]="secondaryText"
      [open]="open"
      [headingsize]="headingSize"
      [testid]="testId"
      [mt]="mt"
      [mb]="mb"
      [ml]="ml"
      [mr]="mr"
    >
      <ng-content select="[slot=headingContent]" />
      <ng-content />
    </goa-accordion>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAAccordion {
  @Input() heading?: string;
  @Input() secondaryText?: string;
  @Input() testId?: string;
  @Input() open?: boolean;
  @Input() headingSize?: GoAAccordionHeadingSize;

  @Input() mt?: string;
  @Input() mb?: string;
  @Input() ml?: string;
  @Input() mr?: string;
}

// libs/react-components/src/lib/accordion/accordion.tsx
import { ReactNode } from "react";

import type { GoAAccordionHeadingSize, Margins } from "@abgov/common";

interface WCProps extends Margins {
  open?: boolean;
  headingSize?: GoAAccordionHeadingSize;
  heading: string;
  secondaryText?: string;
  headingContent?: ReactNode;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-accordion": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoAAccordionProps extends Margins {
  open?: boolean;
  headingSize?: GoAAccordionHeadingSize;
  secondaryText?: string;
  heading: string;
  headingContent?: ReactNode;
  testid?: string;
  children: ReactNode;
}

export function GoAAccordion({
  open,
  heading,
  headingSize,
  secondaryText,
  headingContent,
  testid,
  children,
  mt,
  mr,
  mb,
  ml,
}: GoAAccordionProps): JSX.Element {
  return (
    <goa-accordion
      open={open}
      headingSize={headingSize}
      heading={heading}
      secondaryText={secondaryText}
      data-testid={testid}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    >
      {headingContent && <div slot="headingcontent">{headingContent}</div>}
      {children}
    </goa-accordion>
  );
}

export default GoAAccordion;
