// libs/angular-components/src/lib/components/pagination/pagination.ts
import { GoAPaginationVariant } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

export type GoAPaginationOnChangeDetail = {
  page: number;
}

@Component({
  standalone: true,
  selector: "goax-pagination",
  template: `
    <goa-pagination
      [itemcount]="itemCount"
      [perpagecount]="perPageCount"
      [pagenumber]="pageNumber"
      [variant]="variant"
      [testid]="testId"
      (_change)="_onChange($event)"
    >
    </goa-pagination>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoAPagination {
  @Input({ required: true }) itemCount!: number;
  @Input({ required: true }) pageNumber!: number;
  @Input() perPageCount?: number = 10;
  @Input() variant?: GoAPaginationVariant = "all";
  @Input() testId?: string;

  @Output() onChange = new EventEmitter<GoAPaginationOnChangeDetail>();

  _onChange(e: any) {
    const detail = (e as CustomEvent<GoAPaginationOnChangeDetail>).detail;
    this.onChange.emit(detail)
  }
}

// libs/react-components/src/lib/pagination/pagination.tsx
import { Margins } from "@abgov/common";
import { useEffect, useRef } from "react";

interface WCProps extends Margins {
  ref?: React.MutableRefObject<HTMLElement | undefined>;
  itemcount: number;
  perpagecount?: number;
  pagenumber: number;
  variant?: "all" | "links-only";
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-pagination": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoAPaginationProps extends Margins {
  itemCount: number;
  perPageCount?: number;
  pageNumber: number;
  variant?: "all" | "links-only";
  onChange: (page: number) => void;
  testId?: string;
}

// legacy
export type PaginationProps = GoAPaginationProps;

export function GoAPagination({onChange, ...props}: GoAPaginationProps) {
  const ref = useRef<HTMLElement>();

  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;
    const changeListener = (e: Event) => {
      const { page } = (e as CustomEvent).detail;
      onChange(page);
    };

    current.addEventListener("_change", changeListener);
    return () => {
      current.removeEventListener("_change", changeListener);
    };
  }, [ref, onChange]);

  return (
    <goa-pagination
      ref={ref}
      itemcount={props.itemCount}
      perpagecount={props.perPageCount}
      pagenumber={props.pageNumber}
      variant={props.variant}
      mt={props.mt}
      mb={props.mb}
      ml={props.ml}
      mr={props.mr}
      data-testid={props.testId}
    />
  );
}

export default GoAPagination;
