// libs/react-components/src/lib/skeleton/skeleton.tsx
import { GoASkeletonSize, GoASkeletonType, Margins } from "@abgov/common";

interface WCProps extends Margins {
  maxwidth?: string;
  size?: GoASkeletonSize;
  linecount?: number;
  type: GoASkeletonType;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-skeleton": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoASkeletonProps extends Margins {
  maxWidth?: string;
  size?: GoASkeletonSize;
  lineCount?: number;
  type: GoASkeletonType;
  testId?: string;
}

// legacy name
export type SkeletonProps = GoASkeletonProps;

export const GoASkeleton = ({
  maxWidth,
  size,
  lineCount,
  type,
  testId,
  mt,
  mr,
  mb,
  ml,
}: GoASkeletonProps) => {
  return (
    <goa-skeleton
      maxwidth={maxWidth}
      linecount={lineCount}
      type={type}
      size={size}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      data-testid={testId}
    />
  );
};

export default GoASkeleton;

// libs/angular-components/src/lib/components/skeleton/skeleton.ts
import { GoASkeletonSize, GoASkeletonType } from "@abgov/common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goax-skeleton",
  template: `
    <goa-skeleton
      [maxwidth]="maxWidth"
      [size]="size"
      [linecount]="lineCount"
      [type]="type"
      [testid]="testId"
    >
    </goa-skeleton>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoASkeleton {
  @Input({ required: true }) type!: GoASkeletonType;
  @Input() maxWidth?: string;
  @Input() size?: GoASkeletonSize;
  @Input() lineCount?: number;
  @Input() testId?: string;
}
